/* ═══════════════════════════════════════════════════════════════════════════
   OS GRUPOS DE WHATSAPP
   ═══════════════════════════════════════════════════════════════════════════ */

/* ESTADOS, CIDADES E UNIVERSIDADES ───────────────────────────────────────── */

var ESTADOS = {
  MG: { nome: "Minas Gerais" },
  SP: { nome: "São Paulo" }
};

var CIDADES = {
  bh: { nome: "Belo Horizonte", estado: "MG" },
  contagem: { nome: "Contagem", estado: "MG" },
  juiz_de_fora: { nome: "Juiz de Fora", estado: "MG" },
  sp: { nome: "São Paulo", estado: "SP" }
};

var UNIVERSIDADES_GRUPOS = {
  ufmg: { nome: "UFMG", cidade: "bh" },
  pucmg: { nome: "PUC Minas", cidade: "bh" },
  ufjf: { nome: "UFJF", cidade: "juiz_de_fora" },
  usp: { nome: "USP", cidade: "sp" }
};

/* AS CATEGORIAS ──────────────────────────────────────────────────────────── */

var CATEGORIAS = {
  festas:    { nome: "Festas e Ingressos",  cor: "#A34F76" },
  moradia:   { nome: "Repúblicas",          cor: "#2E7D53" },
  caronas:   { nome: "Grupos de Caronas Soltos", cor: "#3D6E8C" },
  caronas2:  { nome: "Comunidades de Carona de BH", cor: "#8A4B7D" },
  trocas:    { nome: "Desapego e móveis",   cor: "#8C6A3D" },
  compras:   { nome: "Brechó e vestuário",  cor: "#B56576" },
  trabalho:  { nome: "Vagas e serviços",    cor: "#1F7A7A" },
  academico: { nome: "Vida acadêmica",      cor: "#6B5B95" },
  comida:    { nome: "Alimentação",         cor: "#C08A1E" },
  esportes:  { nome: "Esportes e torcidas", cor: "#2B580C" },
  lazer:     { nome: "Lazer e hobbys",      cor: "#B24232" },
  social:    { nome: "Social e paquera",    cor: "#E07A5F" },
  idiomas:   { nome: "Idiomas",             cor: "#8A4B7D" },
  comunidade:{ nome: "Avisos e utilidades", cor: "#4A7C2F" }
};

/* OS GRUPOS ──────────────────────────────────────────────────────────────── */

var GRUPOS = [
  /* ---- Festas e ingressos ---- */
  { nome: "Festas 1 - UFMG", membros: 1024, cat: "festas", uni: "ufmg",
    desc: "Agenda das festas universitárias de BH, com data, local e link de ingresso.",
    url: "https://chat.whatsapp.com/KvPPdy2IoeOE2rSecrUwUf" },
  { nome: "Festas 2 - UFMG", membros: 1024, cat: "festas", uni: "ufmg",
    desc: "Agenda das festas universitárias de BH, com data, local e link de ingresso.",
    url: "https://chat.whatsapp.com/Hl9eTVVoR2ABasYy1TZCAm" },
  { nome: "Festas 3 - UFMG", membros: 1024, cat: "festas", uni: "ufmg",
    desc: "Agenda das festas universitárias de BH, com data, local e link de ingresso.",
    url: "https://chat.whatsapp.com/CQu03yFkhYJ3AWyFKfR3Rb" },
  { nome: "Festas 4 - UFMG", membros: 633, cat: "festas", uni: "ufmg",
    desc: "Agenda das festas universitárias de BH, com data, local e link de ingresso.",
    url: "https://chat.whatsapp.com/HNeYYgemMkiAI7oEWT0TgN" },
  { nome: "Festas 5 - UFMG", membros: 149, cat: "festas", uni: "ufmg",
    desc: "Agenda das festas universitárias de BH, com data, local e link de ingresso.",
    url: "https://chat.whatsapp.com/CwuNjzSvJIJLOSCM8Tb2zZ" },
  { nome: "Festas 6 - UFMG", membros: 184, cat: "festas", uni: "ufmg",
    desc: "Agenda das festas universitárias de BH, com data, local e link de ingresso.",
    url: "https://chat.whatsapp.com/Bp9ZBySZg96Jd4OLI9AU5H" }, 
  { nome: "Rolês espontâneos - UFMG", membros: 184, cat: "festas", uni: "ufmg",
    desc: "Saídas combinadas de última hora: bar, show, praça, o que aparecer.",
    url: "https://chat.whatsapp.com/Lb7EpZmX91rGMDl9LftMFg" },
  { nome: "Venda de ingressos - UFMG", membros: 1024, cat: "festas", uni: "ufmg",
    desc: "Compra, venda e troca de ingressos de festa entre estudantes.",
    url: "https://chat.whatsapp.com/EkltUT5lhocERIMzXZdLeN" },
  { nome: "Venda de ingressos 2 - UFMG", membros: 657, cat: "festas", uni: "ufmg",
    desc: "Compra, venda e troca de ingressos de festa entre estudantes.",
    url: "https://chat.whatsapp.com/BurXGfYKsdcCkCNEuxGcPM" },
  { nome: "Ressaca - UFMG", membros: 0, cat: "festas", uni: "ufmg",
    desc: "Grupo para você que foi em uma festa na ou da UFMG e precisa compartilhar o seu estado de saúde com outros ressacados.",
    url: "https://chat.whatsapp.com/IKa32SEh4CJ1WvjoiAmk31" },

  /* ---- Repúblicas e Moradia ---- */
  { nome: "Repúblicas 1 - UFMG", membros: 1024, cat: "moradia", uni: "ufmg",
    desc: "Vagas, quartos e repúblicas para alugar em Belo Horizonte.",
    url: "https://chat.whatsapp.com/CJ9181tWVpV1c1GdSTgxww" },
  { nome: "Repúblicas 2 - UFMG", membros: 842, cat: "moradia", uni: "ufmg",
    desc: "Vagas, quartos e repúblicas para alugar em Belo Horizonte.",
    url: "https://chat.whatsapp.com/FdgBFBR2SJv6iwQw7D2kG7" },
  { nome: "Repúblicas 3 - UFMG", membros: 0, cat: "moradia", uni: "ufmg",
    desc: "Vagas, quartos e repúblicas para alugar em Belo Horizonte.",
    url: "https://chat.whatsapp.com/HvIJnFaeP70KMqpyDRY5P7" },
  { nome: "Repúblicas perto da Pampulha 1 - UFMG", membros: 1024, cat: "moradia", uni: "ufmg",
    desc: "Vagas e quartos em repúblicas da região da Pampulha, perto do campus.",
    url: "https://chat.whatsapp.com/Ess0ZMOROObCBTTnTiP1F2" },
  { nome: "Repúblicas perto da Pampulha 2 - UFMG", membros: 1024, cat: "moradia", uni: "ufmg",
    desc: "Vagas e quartos em repúblicas da região da Pampulha, perto do campus.",
    url: "https://chat.whatsapp.com/JM03FNZ4vjF1kCddr3Dcyo" },
  { nome: "Repúblicas perto da Pampulha 3 - UFMG", membros: 0, cat: "moradia", uni: "ufmg",
    desc: "Vagas e quartos em repúblicas da região da Pampulha, perto do campus.",
    url: "https://chat.whatsapp.com/Lq1LoFgFC9qEvEfpHgT5Ai" },
  { nome: "Repúblicas perto do Centro - UFMG", membros: 0, cat: "moradia", uni: "ufmg",
    desc: "Vagas e quartos em repúblicas da região central de BH.",
    url: "https://chat.whatsapp.com/LEvKdRVGGLmBZhzuT4YoS3" },
  { nome: "Repúblicas só para mulheres - UFMG", membros: 1024, cat: "moradia", uni: "ufmg",
    desc: "Vagas em repúblicas e moradias compartilhadas só para mulheres.",
    url: "https://chat.whatsapp.com/HRXqNFit0ImHvH2dosm9qd" },
  { nome: "Repúblicas só para mulheres 2 - UFMG", membros: 316, cat: "moradia", uni: "ufmg",
    desc: "Vagas em repúblicas e moradias compartilhadas só para mulheres.",
    url: "https://chat.whatsapp.com/EW1rQywLYyM5X4FaAbBZrp" },

  /* ---- Caronas e viagens ---- */
  { nome: "Vamos embora juntos? Ouro Preto e Castelo - UFMG", membros: 264, cat: "caronas", uni: "ufmg",
    desc: "Caronas de ida e volta para os bairros Ouro Preto e Castelo.",
    url: "https://chat.whatsapp.com/IaYvHkOmYS6LESCBZAXIik" },
  { nome: "Vamos embora juntos? Aeroporto e Jaraguá - UFMG", membros: 97, cat: "caronas", uni: "ufmg",
    desc: "Caronas de ida e volta para os bairros Aeroporto e Jaraguá.",
    url: "https://chat.whatsapp.com/DfyxGad2Q58KccFG7VsjHF" },
  { nome: "Vamos embora juntos? Liberdade e Indaiá - UFMG", membros: 166, cat: "caronas", uni: "ufmg",
    desc: "Caronas de ida e volta para os bairros Liberdade e Indaiá.",
    url: "https://chat.whatsapp.com/KhjFWWaAe8250nZvpTPsQ8" },
  { nome: "Vamos embora juntos? São Francisco e Liberdade - UFMG", membros: 47, cat: "caronas", uni: "ufmg",
    desc: "Caronas de ida e volta para os bairros São Francisco e Liberdade.",
    url: "https://chat.whatsapp.com/F3PzjoNX6OyBwbCy1s3k7t" },
  { nome: "Vamos embora juntos? São José e São Luís - UFMG", membros: 51, cat: "caronas", uni: "ufmg",
    desc: "Caronas de ida e volta para os bairros São José e São Luís.",
    url: "https://chat.whatsapp.com/GcK3vK0yZqlDhc3nWMIEMp" },
  { nome: "Carona Ibirité - UFMG", membros: 107, cat: "caronas", uni: "ufmg",
    desc: "Caronas de ida e volta entre o campus e Ibirité.",
    url: "https://chat.whatsapp.com/BT6JAOxzGiHCWi7Gba6xbk" },
  { nome: "Carona para o Clube do Céu - UFMG", membros: 81, cat: "caronas", uni: "ufmg",
    desc: "Caronas combinadas para os eventos do Clube do Céu.",
    url: "https://chat.whatsapp.com/K3826EQGLIf9ZEDXqkcKq9" },
  { nome: "Férias - UFMG", membros: 283, cat: "caronas", uni: "ufmg",
    desc: "Viagens, bate-voltas e planos para o recesso.",
    url: "https://chat.whatsapp.com/GZot1iRa2DlJVChVI8FweS" },

  /* ---- Comunidades de Carona de BH ---- */
  { nome: "Caronas - Venda Nova - UFMG", membros: 293, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Venda Nova para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/B85Q0g9Aja29JUwq2PRwat" },
  { nome: "Caronas - Norte - UFMG", membros: 298, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Norte para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/DUwGq5RqI42EomOzMPrn35" },
  { nome: "Caronas - Leste - UFMG", membros: 350, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Leste para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/HOE4DUXwktF5zjSFwGSAC6" },
  { nome: "Caronas - Nordeste - UFMG", membros: 277, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Nordeste para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/LHcUdUSXwNg6JsABILkxe6" },
  { nome: "Caronas - Pampulha - UFMG", membros: 713, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Pampulha para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/J8RORwfhKqr66jikVZlBgV" },
  { nome: "Caronas - Oeste - UFMG", membros: 379, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Oeste para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/HCzyjCaUytRJ5UcH1Ak7Lq" },
  { nome: "Caronas - Centro-Sul - UFMG", membros: 1133, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Centro-Sul para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/K6uAf6VRLjC3gSXj6wT9js" },
  { nome: "Caronas - Barreiro - UFMG", membros: 339, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Barreiro para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/KhSNwPUXadLIEjpUnCpmKF" },
  { nome: "Caronas - Noroeste - UFMG", membros: 380, cat: "caronas2", uni: "ufmg",
    desc: "Comunidade de caronas com grupos da região Noroeste para a UFMG, reunindo subgrupos específicos dos bairros locais.",
    url: "https://chat.whatsapp.com/HSvSJbNEW186Wxz3sOjdfg" },

  /* ---- Desapego e trocas gerais ---- */
  { nome: "Desapego 1 - UFMG", membros: 1024, cat: "trocas", uni: "ufmg",
    desc: "Móveis, eletrônicos e tralha de república à venda por preço de estudante.",
    url: "https://chat.whatsapp.com/GnBXA8rrKEn1sh5SpMmKpt" },
  { nome: "Desapego 2 - UFMG", membros: 783, cat: "trocas", uni: "ufmg",
    desc: "Móveis, eletrônicos e tralha de república à venda por preço de estudante.",
    url: "https://chat.whatsapp.com/I7rvb0XmtOU13o7eZtgvPk" },
  { nome: "Desapego 3 - UFMG", membros: 862, cat: "trocas", uni: "ufmg",
    desc: "Móveis, eletrônicos e tralha de república à venda por preço de estudante.",
    url: "https://chat.whatsapp.com/HA2BSkPRHuV8F8g3N9hjOa" },
  { nome: "Desapego 4 - UFMG", membros: 1024, cat: "trocas", uni: "ufmg",
    desc: "Móveis, eletrônicos e tralha de república à venda por preço de estudante.",
    url: "https://chat.whatsapp.com/BQ4FXZQnQy61DrO0PZJL0C" },
  { nome: "Desapego 5 - UFMG", membros: 712, cat: "trocas", uni: "ufmg",
    desc: "Móveis, eletrônicos e tralha de república à venda por preço de estudante.",
    url: "https://chat.whatsapp.com/DGmKSrvX0gb1WwR8RnKMxC" },
  { nome: "Desapego 6 - UFMG", membros: 0, cat: "trocas", uni: "ufmg",
    desc: "Móveis, eletrônicos e tralha de república à venda por preço de estudante.",
    url: "https://chat.whatsapp.com/Ggh6Tz6UDCWIA9Wk3jIjPi" },
  { nome: "Doa-se 1 - UFMG", membros: 1024, cat: "trocas", uni: "ufmg",
    desc: "Só doação: móveis, roupas e utensílios que alguém não usa mais.",
    url: "https://chat.whatsapp.com/GjCgDGrWG3HHvm4LoGR8eC" },
  { nome: "Doa-se 2 - UFMG", membros: 1024, cat: "trocas", uni: "ufmg",
    desc: "Só doação: móveis, roupas e utensílios que alguém não usa mais.",
    url: "https://chat.whatsapp.com/KPEslIuLO7M2LQIEsVthZV" },
  { nome: "Doa-se 3 - UFMG", membros: 0, cat: "trocas", uni: "ufmg",
    desc: "Só doação: móveis, roupas e utensílios que alguém não usa mais.",
    url: "https://chat.whatsapp.com/F620YB5Iygb2uhxlxrXxCf" },
  { nome: "Só permutas - UFMG", membros: 313, cat: "trocas", uni: "ufmg",
    desc: "Só troca, sem dinheiro no meio: item por item.",
    url: "https://chat.whatsapp.com/KSvvBGfDtlkILymLGNjmrd" },
  { nome: "Sebo - UFMG", membros: 1024, cat: "trocas", uni: "ufmg",
    desc: "Compra, venda e troca de livros usados, acadêmicos ou não.",
    url: "https://chat.whatsapp.com/B6FWVTaDXiw79NI6CP6RF8" },
  { nome: "Sebo 2 - UFMG", membros: 649, cat: "trocas", uni: "ufmg",
    desc: "Compra, venda e troca de livros usados, acadêmicos ou não.",
    url: "https://chat.whatsapp.com/FQg85lti2LPLVeknXkJKGw" },

  /* ---- Brechó e vestuário ---- */
  { nome: "Bazar 1 - UFMG", membros: 1024, cat: "compras", uni: "ufmg",
    desc: "Bazar de roupas, calçados e acessórios entre estudantes.",
    url: "https://chat.whatsapp.com/BA8BiS15IeQ3Q1OI9LfFNE" },
  { nome: "Bazar 2 - UFMG", membros: 1024, cat: "compras", uni: "ufmg",
    desc: "Bazar de roupas, calçados e acessórios entre estudantes.",
    url: "https://chat.whatsapp.com/IEjkqVFVUqy8xRz386E8JC" },
  { nome: "Bazar 3 - UFMG", membros: 0, cat: "compras", uni: "ufmg",
    desc: "Bazar de roupas, calçados e acessórios entre estudantes.",
    url: "https://chat.whatsapp.com/FkjsrejdRUhAUf37hRlqJl" },
  { nome: "Bazar plus size feminino - UFMG", membros: 126, cat: "compras", uni: "ufmg",
    desc: "Bazar de roupas femininas plus size, com venda e troca.",
    url: "https://chat.whatsapp.com/LHH3vz8uXz59N09BqmBpUT" },
  { nome: "Brechó feminino - UFMG", membros: 966, cat: "compras", uni: "ufmg",
    desc: "Brechó de roupas femininas: venda, troca e garimpo.",
    url: "https://chat.whatsapp.com/Hz20t5ZgWwWKO8whhG3gMo" },
  { nome: "Brechó feminino 2 - UFMG", membros: 30, cat: "compras", uni: "ufmg",
    desc: "Brechó de roupas femininas: venda, troca e garimpo.",
    url: "https://chat.whatsapp.com/J7agv9Vofhl4zQjtzZjP2x" },
  { nome: "Brechó masculino - UFMG", membros: 1004, cat: "compras", uni: "ufmg",
    desc: "Brechó de roupas masculinas: venda, troca e garimpo.",
    url: "https://chat.whatsapp.com/D0sRKXG9rAOJQwwGJNho6v" },
  { nome: "Brechó masculino 2 - UFMG", membros: 0, cat: "compras", uni: "ufmg",
    desc: "Brechó de roupas masculinas: venda, troca e garimpo.",
    url: "https://chat.whatsapp.com/KqxLeT1rxH2GfncfygI7RV" },

  /* ---- Vagas, estágios e serviços ---- */
  { nome: "Free-lancers 1 - UFMG", membros: 1024, cat: "trabalho", uni: "ufmg",
    desc: "Trabalhos avulsos e bicos: quem precisa e quem faz se encontram aqui.",
    url: "https://chat.whatsapp.com/FJ56dr6ptaIAcIrXuz5KAW" },
  { nome: "Free-lancers 2 - UFMG", membros: 1024, cat: "trabalho", uni: "ufmg",
    desc: "Trabalhos avulsos e bicos: quem precisa e quem faz se encontram aqui.",
    url: "https://chat.whatsapp.com/DA4G7huHvOKARnf9SZ2End" },
  { nome: "Free-lancers 3 - UFMG", membros: 1024, cat: "trabalho", uni: "ufmg",
    desc: "Trabalhos avulsos e bicos: quem precisa e quem faz se encontram aqui.",
    url: "https://chat.whatsapp.com/CcHu3q40VrYIMoUyUrd6A4" },
  { nome: "Free-lancers 4 - UFMG", membros: 1024, cat: "trabalho", uni: "ufmg",
    desc: "Trabalhos avulsos e bicos: quem precisa e quem faz se encontram aqui.",
    url: "https://chat.whatsapp.com/Kmj1ckcnfud4z3uY9wtBF0" },
  { nome: "Free-lancers 5 - UFMG", membros: 1024, cat: "trabalho", uni: "ufmg",
    desc: "Trabalhos avulsos e bicos: quem precisa e quem faz se encontram aqui.",
    url: "https://chat.whatsapp.com/LQ3QCYUigcb12WujTyfaxg" },
  { nome: "Free-lancers 6 - UFMG", membros: 1024, cat: "trabalho", uni: "ufmg",
    desc: "Trabalhos avulsos e bicos: quem precisa e quem faz se encontram aqui.",
    url: "https://chat.whatsapp.com/J2nkArDP6WQ70ehzM29m3A" },
  { nome: "Free-lancers 7 - UFMG", membros: 76, cat: "trabalho", uni: "ufmg",
    desc: "Trabalhos avulsos e bicos: quem precisa e quem faz se encontram aqui.",
    url: "https://chat.whatsapp.com/BAwsWMLxMwP1MTq9RM1KZt" },
  { nome: "Estágios 1 - UFMG", membros: 1024, cat: "trabalho", uni: "ufmg",
    desc: "Vagas de estágio abertas para quem ainda está na graduação.",
    url: "https://chat.whatsapp.com/FEoxKtC1ffGEJxkZSsMRw9" },
  { nome: "Estágios 2 - UFMG", membros: 980, cat: "trabalho", uni: "ufmg",
    desc: "Vagas de estágio abertas para quem ainda está na graduação.",
    url: "https://chat.whatsapp.com/Da4r3Ne3Kf11rIPVWHcnts" },
  { nome: "Estágios 3 - UFMG", membros: 0, cat: "trabalho", uni: "ufmg",
    desc: "Vagas de estágio abertas para quem ainda está na graduação.",
    url: "https://chat.whatsapp.com/LZriRvZbQ4HKktIzBRIwab" },
  { nome: "Vagas CLT 1 - UFMG", membros: 930, cat: "trabalho", uni: "ufmg",
    desc: "Vagas de emprego com carteira assinada em BH e região.",
    url: "https://chat.whatsapp.com/CbMy8JwuOBUDjYCQGMq3cy" },
  { nome: "Vagas CLT 2 - UFMG", membros: 255, cat: "trabalho", uni: "ufmg",
    desc: "Vagas de emprego com carteira assinada em BH e região.",
    url: "https://chat.whatsapp.com/KkaKW4ScNcu81QMqNU62X9" },
  { nome: "Prestadores de serviços - UFMG", membros: 898, cat: "trabalho", uni: "ufmg",
    desc: "Serviços de estudantes: aulas particulares, design, reforma, transporte.",
    url: "https://chat.whatsapp.com/IWnlDLEzClx17WynFmnr6I" },
  { nome: "Prestadores de serviços 2 - UFMG", membros: 0, cat: "trabalho", uni: "ufmg",
    desc: "Serviços de estudantes: aulas particulares, design, reforma, transporte.",
    url: "https://chat.whatsapp.com/FeiE3GGSjfC89ge8O6qyZH" },
  { nome: "Concursos públicos 1 - UFMG", membros: 838, cat: "trabalho", uni: "ufmg",
    desc: "Editais, prazos e materiais de estudo para concursos.",
    url: "https://chat.whatsapp.com/DEzhqvHFQgS463CEe0wzI2" },
  { nome: "Concursos públicos 2 - UFMG", membros: 385, cat: "trabalho", uni: "ufmg",
    desc: "Editais, prazos e materiais de estudo para concursos.",
    url: "https://chat.whatsapp.com/INGpcrRNKxI3EcIrxtOuCj" },

  /* ---- Vida acadêmica ---- */
  { nome: "Calouros - UFMG", membros: 754, cat: "academico", uni: "ufmg",
    desc: "Primeiros passos na UFMG: matrícula, bandejão, transporte e o que mais assustar.",
    url: "https://chat.whatsapp.com/KWtvZdKuSgm3xnf4FPSTSY" },
  { nome: "Tirar dúvidas - UFMG", membros: 739, cat: "academico", uni: "ufmg",
    desc: "Dúvida de matéria, de prova e de trabalho, respondida pela comunidade.",
    url: "https://chat.whatsapp.com/CWq0RGEw1SYC57dIVH59kd" },
  { nome: "Notícias acadêmicas - UFMG", membros: 759, cat: "academico", uni: "ufmg",
    desc: "Avisos de matrícula, calendário, editais e o que acontece na universidade.",
    url: "https://chat.whatsapp.com/GUQfUse63WVB7PiOfJf77U" },
  { nome: "Projetos de extensão 1 - UFMG", membros: 1024, cat: "academico", uni: "ufmg",
    desc: "Chamadas de projeto de extensão, pesquisa e monitoria.",
    url: "https://chat.whatsapp.com/JV2YTI4XIFoBqPDU5ue244" },
  { nome: "Projetos de extensão 2 - UFMG", membros: 18, cat: "academico", uni: "ufmg",
    desc: "Chamadas de projeto de extensão, pesquisa e monitoria.",
    url: "https://chat.whatsapp.com/E77F4kGe7en9VYGP02xRc5" },
  { nome: "Liga acadêmica do coffee break - UFMG", membros: 569, cat: "academico", uni: "ufmg",
    desc: "Onde tem coffee break de graça no campus hoje.",
    url: "https://chat.whatsapp.com/HYTd6wLd1Tz0iLHM1JOGEq" }
];